# Generated by Django 2.2.10 on 2020-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='identification',
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
