# Generated by Django 2.2.12 on 2020-04-16 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('営業', '営業部'), ('経理', '経理部'), ('人事', '人事部'), ('IT', 'IT部')], default='営業部', max_length=5, verbose_name='部署'),
        ),
        migrations.CreateModel(
            name='Loan_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(blank=True, null=True, verbose_name='start loan date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='return date')),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所持者')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register.Equipment', verbose_name='備品')),
            ],
        ),
    ]
