# Generated by Django 2.2.12 on 2020-04-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200416_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_log',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('PC', 'PC'), ('カメラ', 'カメラ'), ('プロジェクター', 'プロジェクター'), ('その他', 'その他')], default='PC', max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.CreateModel(
            name='Return_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='return date')),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所持者')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register.Equipment', verbose_name='備品')),
            ],
        ),
    ]
