# Generated by Django 2.2.10 on 2020-03-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200317_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='belong_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所持者'),
        ),
    ]
