# Generated by Django 2.2.10 on 2020-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200317_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('PC', 'PC'), ('カメラ', 'カメラ'), ('プロジェクター', 'プロジェクター'), ('その他', 'その他')], default='PC', max_length=5),
        ),
        migrations.AddField(
            model_name='equipment',
            name='comment',
            field=models.TextField(null=True, verbose_name='概要'),
        ),
    ]
