# Generated by Django 2.2.10 on 2020-03-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200317_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('PC', 'PC'), ('カメラ', 'カメラ'), ('プロジェクター', 'プロジェクター'), ('その他', 'その他')], default='PC', max_length=5, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='備品名称'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(default=0, verbose_name='購入費用'),
        ),
    ]
